### PR TITLE
Update gost_ec_keyx.c

### PR DESCRIPTION
**Pull request by se-prok**
It's not right to have segmentation faults.

### CODE REVIEW

**Comment by beldmit** [comment]
Merged. Thanks!

**Comment by se-prok** [comment]
Please note that null point is not the same as null pointer :). Therefore above {-TODO: beldmit...-} section still has to be done.

**Comment by beldmit** [comment]
@se-prok, iIf I implement the patch fixing this TODO, will you be able to test it?

**Comment by se-prok** [comment]
yup

**Comment by beldmit** [comment]
[TODOfix.txt](https://github.com/gost-engine/engine/files/6259306/TODOfix.txt)

@se-prok please take a look

**Comment by se-prok** [comment]
quick test says that using the wrong curve when calculating public key to be sent to openssl is caught both with and without this patch: openssl responds with the error "elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on curve:crypto/ec/ec_lib.c:877:"

**Comment by beldmit** [comment]
And 2 other checks?

**Comment by se-prok** [comment]
The same reaction ("...point is not on curve...") to any tested misrepresentation of public key including point (0,0). Both with and without the patch.

**Pull request merged**
