### PR TITLE
Remove the use of test/run_tests in favor of 'prove'

### PR DESCRIPTION
**Pull request by levitte**
'prove' is a well developed TAP harness program, there's no real need
to write one's own.

We do need to set certain paths properly for the appropriate 'openssl'
program to be run.  We do that with a 'prove' plugin (WrapOpenSSL.pm)
that simply amends the appropriate system environment variables, given
a number of cmake generated environment variables that indicate where
OpenSSL files reside.

### CODE REVIEW

**Comment by beldmit** [comment]
Is is a standalone PR?

**Comment by levitte** [comment]
> Is is a standalone PR?

Yes.  That's how I usually try to do things (when some PRs depend on others I try to mark them thusly...  I'm sure you've seen my '[Pending on #xxx]' over in OpenSSL).
(I do realise that I haven't made such marks on #313, but that one's still in draft, so I care less...  I hope that what it depends on will be merged soon enough)

**Comment by beldmit** [comment]
@mouse07410 would you mind to test it before it gets merged?

**Comment by beldmit** [comment]
Merged. Many thanks!

**Pull request merged**
