### PR TITLE
Remove 'set -e' in Travis-CI. It can cause weird behaviour

### PR DESCRIPTION
**Pull request by vt-alt**
Improved PR#307

### CODE REVIEW

**Comment by vt-alt** [comment]
Опять Travis-CI не пашет?

**Comment by vt-alt** [comment]
> Опять Travis-CI не пашет?

https://travis-ci.com/github/gost-engine/engine/pull_requests
 "Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting."

**Comment by beldmit** [comment]
OpenSSL как-то по-другому проблему с кредитами решил, кажется.

**Comment by vt-alt** [comment]
Пишут, что надо (каждый раз?) делать запрос https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

_We will be offering an allotment of OSS minutes that **will be reviewed and allocated on a case by case basis**. Should you want to apply for these credits please **open a request** with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
Your account name and VCS provider (like travis-ci.com/github/[your account name] )
How many credits (build minutes) you’d like to request (should your run out of credits again you can **repeat the process to request more or discuss a renewable amount**)_

Можно перейти на GitHub Actions. Правда, там меньше архитектур.

**Comment by beldmit** [comment]
Вот лучше, наверное, github actions

**Comment by vt-alt** [comment]
А у них там follow-up есть https://blog.travis-ci.com/oss-announcement -- OpenSSL настолько важный проект для их пиара, что они его готовы бесплатно собирать, а для остальных -- "brought the abuse of open source at Travis CI under control"!

**Comment by vt-alt** [comment]
https://github.com/strace/strace/commit/848fbc14f4441765493464376c103e953a7fe130

**Comment by beldmit** [comment]
Зааппрувить-то я это могу, но смысл пока непонятен.

**Comment by vt-alt** [comment]
Я бы пока оставил Травис, на случай, если они ещё предложат хорошие условия для OSS. Всё таки - разные архитектуры были полезны.

**Comment by levitte** [comment]
> "Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting."

OpenSSL stopped using Travis for this reason.  Furthermore, I find Github actions to be easier to manage

**Comment by vt-alt** [comment]
@levitte Thanks for the info on that!

**Comment by beldmit** [comment]
closing as Travis is not used anymore.

**Comment by vt-alt** [comment]
It seems that Travis is still free for all secondary architectures (i.e. excluding x86/amd64):
https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution
```
Partner Queue Solution is a solution for infrastructure sponsored by our Partners
with OSS in mind which can be used completely for free. Currently, it includes:
 - IBM CPU builds in IBM Cloud (sponsored by IBM)
 - ARM64 CPU builds in Equinix Metal (former Packet) infrastructure (sponsored by ARM)
This is available only to Open Source Software repositories.
```

**Comment by beldmit** [comment]
ну можно пробовать реанимировать...

**Pull request closed without merging**
