### PR TITLE
test_tls: Introduce timeouts into test to make it not hang

### PR DESCRIPTION
**Pull request by vt-alt**
Handle abnormal exit of s_client/s_server processes.

Fixes partially #230.

### CODE REVIEW

**Comment by vt-alt** [comment]
OK, need to fix ASan and Freebsd build.

**Comment by vt-alt** [comment]
Now, need to fix for os x, it's turned out it doesn't have `sigtimedwait`. https://www.gnu.org/software/gnulib/manual/html_node/sigtimedwait.html

**Comment by vt-alt** [comment]
Simplified the code, removed timeouts, but still should be enough for an accidental openssl error. Travis tests all green.

**Comment by beldmit** [comment]
Спасибо!

**Pull request merged**
