### PR TITLE
Make gost-engine independent of OpenSSL SOURCE

### PR DESCRIPTION
**Pull request by levitte**
It really already was, this only removes artifacts in CMakeLists.txt

### CODE REVIEW

**Comment by beldmit** [comment]
Dear Richard,
I do not understand this commit :(
If I understand correctly, after this commit I will be unable to build the engine using a local copy of OpenSSL.

**Comment by mouse07410** [comment]
> If I understand correctly, after this commit I will be unable to build the engine using a local copy of OpenSSL.

In my view, the whole point is to **not** have to keep a local source tree of OpenSSL in order to build this engine. So you could **install** your local OpenSSL build to somewhere, and point this build to that (temporary?) installation.

Though I don't fully understand: the idea of an engine is to build some code that can run together with the existing binary OpenSSL installation. If you're willing to muck with the OpenSSL source - why do you need an engine at all?

**Comment by mouse07410** [comment]
@levitte may I ask you to take a look at 1.0.2 branch of this repo? It would be great if your (another?) PR could be applied to it, so one can build this engine for a binary distribution of 1.0.2 (say, 1.0.2l).

**Comment by levitte** [comment]
> If I understand correctly, after this commit I will be unable to build the engine using a local copy of OpenSSL.

Not true, you can use `CMAKE_C_FLAGS` to add the approriate flags.  For example, I built against a local 1.1.1-dev installation like this:

```
$ mkdir build
$ (cd build; cmake -DCMAKE-C-FLAGS='-I/PATH/TO/_install/include -L/PATH/TO/_install/lib')
$ (cd build; make)
```

**Comment by levitte** [comment]
> @levitte may I ask you to take a look at 1.0.2 branch of this repo? It would be great if your (another?) PR could be applied to it, so one can build this engine for a binary distribution of 1.0.2 (say, 1.0.2l).

Sure, I'll have a look at that tomorrow.

**Comment by beldmit** [comment]
1. Richard, could you please add mentioning the 
$ mkdir build
$ (cd build; cmake -DCMAKE-C-FLAGS='-I/PATH/TO/_install/include -L/PATH/TO/_install/lib')
$ (cd build; make)

to the CMake_ReadMe.md and fix conflicts?

2. Regarding 1.0.2 branch, it is designed as drop-in replacement of the version present in openssl 1.0.2, but we need patch the tree to provide all the necessary OIDs. I'll update the documentation soon.

Thank you very much!

**Comment by mouse07410** [comment]
> Regarding 1.0.2 branch, it is designed as drop-in replacement of the version present in openssl 1.0.2, but we need patch the tree to provide all the necessary OIDs

Is there **any** way around this? Maybe with some functionality sacrificed?

**Comment by beldmit** [comment]
If we sacrify anything, you can just take the engine from openssl 1.0.2

You may try to register OIDs/NIDs dynamically, but you'll have to sacrify GOST support in PKCS12.

**Comment by levitte** [comment]
> 1. Richard, could you please add mentioning the

Done

**Comment by mouse07410** [comment]
> You may try to register OIDs/NIDs dynamically,

An excellent idea, if you ask me.

> but you'll have to sacrifice GOST support in PKCS12.

I'm not certain this is correct.

**Comment by beldmit** [comment]
Thank you very much!

**Pull request merged**
