### PR TITLE
 Add native Visual Studio 2015-2017 build support

### PR DESCRIPTION
**Pull request by DJm00n**

### CODE REVIEW

**Comment by beldmit** [comment]
After applying patch I get the following errors:

=========
beldmit@manul$ cmake .
CMake Error: Could not find cmake module file: CMakeDetermineDESCRIPTIONCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_DESCRIPTION_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_DESCRIPTION_COMPILER
CMake Error: Could not find cmake module file: /home/beldmit/hobby/crypto/engine/engine/CMakeFiles/3.7.2/CMakeDESCRIPTIONCompiler.cmake
CMake Error: Could not find cmake module file: CMakeDetermineReference implementation of GOST engine for OpenSSLCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_Reference implementation of GOST engine for OpenSSL_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_Reference implementation of GOST engine for OpenSSL_COMPILER
CMake Error: Could not find cmake module file: /home/beldmit/hobby/crypto/engine/engine/CMakeFiles/3.7.2/CMakeReference implementation of GOST engine for OpenSSLCompiler.cmake
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_DESCRIPTION_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_DESCRIPTION_COMPILER to the full path to the compiler, or to the
  compiler name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakeDESCRIPTIONInformation.cmake
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_Reference implementation of GOST engine for OpenSSL_COMPILER could
  be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_Reference implementation of GOST engine for OpenSSL_COMPILER to the
  full path to the compiler, or to the compiler name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakeReference implementation of GOST engine for OpenSSLInformation.cmake
CMake Error: CMAKE_DESCRIPTION_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_Reference implementation of GOST engine for OpenSSL_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/beldmit/hobby/crypto/engine/engine/CMakeFiles/CMakeOutput.log".
=======

**Comment by DJm00n** [comment]
@beldmit try to delete `DESCRIPTION "Reference implementation of GOST engine for OpenSSL"` in CMakeLists.txt:2. It seems this feature was introduced in CMake 3.9.
I will update PR if it helps.

**Comment by beldmit** [comment]
Partially helps, but 

beldmit@manul$ make
Scanning dependencies of target gost_core
[  3%] Building C object CMakeFiles/gost_core.dir/gost89.c.o
cc: error: unrecognized command line option ‘-std=c98’; did you mean ‘-std=c90’?
CMakeFiles/gost_core.dir/build.make:62: ошибка выполнения рецепта для цели «CMakeFiles/gost_core.dir/gost89.c.o»
make[2]: *** [CMakeFiles/gost_core.dir/gost89.c.o] Ошибка 1
CMakeFiles/Makefile2:67: ошибка выполнения рецепта для цели «CMakeFiles/gost_core.dir/all»
make[1]: *** [CMakeFiles/gost_core.dir/all] Ошибка 2
Makefile:127: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by beldmit** [comment]
In case of changing -std=c99 the errors are

[ 89%] Building C object CMakeFiles/gostsum.dir/gostsum.c.o
/home/beldmit/hobby/crypto/engine/engine/gostsum.c: In function ‘main’:
/home/beldmit/hobby/crypto/engine/engine/gostsum.c:59:17: error: implicit declaration of function ‘getopt’ [-Werror=implicit-function-declaration]
     while ((c = getopt(argc, argv, "bc::tv")) != -1) {
                 ^~~~~~
/home/beldmit/hobby/crypto/engine/engine/gostsum.c:71:17: error: ‘optarg’ undeclared (first use in this function)
             if (optarg) {
                 ^~~~~~
/home/beldmit/hobby/crypto/engine/engine/gostsum.c:71:17: note: each undeclared identifier is reported only once for each function it appears in
/home/beldmit/hobby/crypto/engine/engine/gostsum.c:82:50: error: ‘optopt’ undeclared (first use in this function)
             fprintf(stderr, "invalid option %c", optopt);
                                                  ^~~~~~
/home/beldmit/hobby/crypto/engine/engine/gostsum.c:88:48: error: ‘PATH_MAX’ undeclared (first use in this function)
         char inhash[65], calcsum[65], filename[PATH_MAX];
                                                ^~~~~~~~
/home/beldmit/hobby/crypto/engine/engine/gostsum.c:91:36: error: ‘optind’ undeclared (first use in this function)
         if (check_file == stdin && optind < argc) {
                                    ^~~~~~
/home/beldmit/hobby/crypto/engine/engine/gostsum.c:88:39: error: unused variable ‘filename’ [-Werror=unused-variable]
         char inhash[65], calcsum[65], filename[PATH_MAX];
                                       ^~~~~~~~
/home/beldmit/hobby/crypto/engine/engine/gostsum.c:139:32: error: implicit declaration of function ‘fileno’ [-Werror=implicit-function-declaration]
         if (!hash_stream(&ctx, fileno(stdin), sum)) {
                                ^~~~~~
/home/beldmit/hobby/crypto/engine/engine/gostsum.c: In function ‘get_line’:
/home/beldmit/hobby/crypto/engine/engine/gostsum.c:208:32: error: ‘PATH_MAX’ undeclared (first use in this function)
     i = strlen(fgets(filename, PATH_MAX, f));
                                ^~~~~~~~
cc1: all warnings being treated as errors

**Comment by beldmit** [comment]
I also think that while minimal standard version for OpenSSL is C90, it is not a good idea to require C99 in engine, at least for Unix-like systems.

**Comment by DJm00n** [comment]
I updated CMakeLists.txt to use c90 std plus some minor tweaks.
Tested building and installing with _VS2017 x64 / cmake 3.10_ and _mingw64 / gcc 7.2.0 / cmake 3.3_.

**Comment by beldmit** [comment]
Thank you. Applied.

**Pull request merged**
