### PR TITLE
Add LICENSE file to satisfy the lawyer in you

### PR DESCRIPTION
**Pull request by mojoman**
Due to popular request, please add LICENSE file in the source code :)

### CODE REVIEW

**Comment by levitte** [comment]
Why should it be the OpenSSL license?  Seriously, I find the choice very questionable, especially seeing that we at OpenSSL are working (albeit slowly or the moment) on replacing it for OpenSSL proper.

Please make a different choice.  There are a number of modern licenses to choose from.  Github actually has a number of proposed choices for new projects.

**Comment by levitte** [comment]
Meh, I see that the README mentions the OpenSSL license.

**Comment by beldmit** [comment]
Well, as the engine can't be used without OpenSSL, it seems reasonable to use the same terms as the corresponding version of OpenSS

**Comment by levitte** [comment]
I'm forgetting that the GOST engine started off as an integral part of the OpenSSL source code...  so it was already licensed that way before getting pulled out into its own project.  So yeah, that makes this license more understandable, and makes this project a special case.

Generally speaking, creators of independent engines should not feel obligated to use the OpenSSL license, whichever it is.

**Pull request closed without merging**
