### PR TITLE
Cert/pub_key/priv_key PEM/DER conversion tests

### PR DESCRIPTION
**Pull request by vt-alt**
I wanted to test this error https://github.com/openssl/openssl/issues/11861
Also, I found this error https://github.com/openssl/openssl/issues/11870

### CODE REVIEW

**Comment by vt-alt** [comment]
Currently, tests should not fail, because `OSSL_STORE_attach` test is skipped. Please. wait one day before merging. Or maybe we should wait for `OSSL_STORE_attach` fix.

**Comment by beldmit** [comment]
Close/open to rerun Travis

**Comment by beldmit** [comment]
Close / open to rerun Travis

**Comment by beldmit** [comment]
Спасибо!

**Pull request merged**
