### PR TITLE
gost 34.11-2012. memory usage and performance improvements

### PR DESCRIPTION
**Pull request by ddulesov**

### CODE REVIEW

**Comment by vt-alt** [comment]
1. Tested on sparc64 (UltraSparc T5) - pass.
2. `init_gost2012_hash_ctx` - good
3. `pad` - "unreachable condition" should be assert not just `return`.
4. `add512` code looks familiar, but why three-way if-else and `y->QWORD[i]` used three times instead of one variable? Even simpler version: https://github.com/adegtyarev/streebog/commit/432d5de6633251
5. `stage2`, `stage3`, `gost2012_hash_block` what point in all these code rearrangements?
6. Show "performance improvements" numbers. There is mine:
```
master:
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
md_gost_12_256     3514.32k    12126.63k    30484.57k    49104.21k    59919.02k    60855.64k
md_gost_12_512     3772.18k    12138.23k    30452.22k    49071.45k    59883.52k    60839.25k

pr/190:
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
md_gost_12_256     3544.59k    12163.65k    30118.14k    48694.95k    58045.78k    59370.15k
md_gost_12_512     3814.56k    12188.59k    30330.71k    48455.00k    58594.65k    59523.07k
```
It became slower (test on E5630).
7. Why horrible formatting and useless comments like `//memcpy ...`, why not split into meaningful and easier to review smaller patches.

**Comment by ddulesov** [comment]
Hi,
1.  Ok
2.  Ok
3.  I've just  commented existen code.  Ok will add assert.
4.  Yes.


I've corrected original/master function that used not optimal  big integer
addition algorithm.
@ adegtyarev/streebog@432d5de
<https://github.com/adegtyarev/streebog/commit/432d5de6633251>  version is
well.
My code of add512 as well as given by @ adegtyarev/streebog@432d5de
<https://github.com/adegtyarev/streebog/commit/432d5de6633251>  have the
same idea. I prefer write explicitly as
```
if (tmp == x[i]){
//CF not changed
}else if (tmp < x->QWORD[i])
            CF = 1; //overflow
        else
            CF = 0; //no overflow
```
the same action can be written implicitly . with comments
  ```
tmp = x[i] + y[i] + CF;

if (tmp != x[i])
            CF = (tmp < x[i] );

x[i] = tmp;
```
or as a tradeoff
     ```
tmp = x[i] + y[i] + CF;

if (tmp != x[i])
            CF = (tmp < x[i] )?1: 0 ;

x[i] = tmp;
```

I think it's a matter of opinion.
Moreover, both code blocks generate identical machine instructions.

It's slightly modified function declaration for https://godbolt.org/
 demonstration

https://godbolt.org/z/pePb6n

```c
inline void add512(unsigned long long  *x, unsigned long long *y)
{

    unsigned int CF=0;
    unsigned long long tmp;
    unsigned int i;

    for (i = 0; i < 8; i++)
    {

        tmp = x[i] + y[i] + CF;

if (tmp == x[i]){
//CF not changed
}else if (tmp < x->QWORD[i])
            CF = 1; //overflow
        else
            CF = 0; //no overflow
x[i] = tmp;

    }
}
```
Resulted machine instructions

 x86-64 gcc 8.3  (-O2)
-------------------------------------------------
add512(unsigned long long*, unsigned long long*):
        xor     eax, eax
        xor     ecx, ecx
.L3:
        mov     r8, QWORD PTR [rdi+rax]
        mov     rdx, QWORD PTR [rsi+rax]
        mov     r9d, ecx
        add     rdx, r8
        add     rdx, r9
        xor     r9d, r9d
;only one comparison
        cmp     r8, rdx
        mov     QWORD PTR [rdi+rax], rdx
        seta    r9b
        cmovne  ecx, r9d
        add     rax, 8
        cmp     rax, 64
        jne     .L3
        ret


  x86-64 clang 6.0 (-O2)
 ------------------
add512(unsigned long long*, unsigned long long*):
        mov     rax, qword ptr [rsi]
        mov     rcx, qword ptr [rdi]
        add     rcx, rax
        setb    dl
        test    rax, rax
        setne   al
        and     al, dl
        mov     qword ptr [rdi], rcx
        movzx   edx, al
        mov     rcx, qword ptr [rdi + 8]
        mov     r9, qword ptr [rdi + 16]
        add     rdx, rcx
        add     rdx, qword ptr [rsi + 8]
        cmp     rdx, rcx
        setb    r8b
        je      .LBB0_2
        mov     eax, r8d
.LBB0_2:
        mov     qword ptr [rdi + 8], rdx
        movzx   edx, al
        add     rdx, r9
        add     rdx, qword ptr [rsi + 16]
        cmp     rdx, r9
        setb    cl
        je      .LBB0_4
        mov     eax, ecx
.LBB0_4:
        mov     qword ptr [rdi + 16], rdx
        mov     rdx, qword ptr [rdi + 24]
        movzx   ecx, al
        add     rcx, rdx
        add     rcx, qword ptr [rsi + 24]
        cmp     rcx, rdx
        setb    dl
        je      .LBB0_6
        mov     eax, edx
.LBB0_6:
        mov     qword ptr [rdi + 24], rcx
        mov     rdx, qword ptr [rdi + 32]
        movzx   ecx, al
        add     rcx, rdx
        add     rcx, qword ptr [rsi + 32]
        cmp     rcx, rdx
        setb    dl
        je      .LBB0_8
        mov     eax, edx
.LBB0_8:
        mov     qword ptr [rdi + 32], rcx
        mov     rdx, qword ptr [rdi + 40]
        movzx   ecx, al
        add     rcx, rdx
        add     rcx, qword ptr [rsi + 40]
        cmp     rcx, rdx
        setb    dl
        je      .LBB0_10
        mov     eax, edx
.LBB0_10:
        mov     qword ptr [rdi + 40], rcx
        mov     rdx, qword ptr [rdi + 48]
        movzx   ecx, al
        and     ecx, 1
        add     rcx, rdx
        add     rcx, qword ptr [rsi + 48]
        cmp     rcx, rdx
        setb    dl
        je      .LBB0_12
        mov     eax, edx
.LBB0_12:
        mov     qword ptr [rdi + 48], rcx
        movzx   eax, al
        and     eax, 1
        add     rax, qword ptr [rdi + 56]
        add     rax, qword ptr [rsi + 56]
        mov     qword ptr [rdi + 56], rax
        ret


# adegtyarev/streebog@432d5de
<https://github.com/adegtyarev/streebog/commit/432d5de6633251>   version
------------------------------------------------------------------
void add512(unsigned long long  *x, unsigned long long *y)
{

    unsigned int CF=0;
    unsigned long long tmp;
    unsigned int i;

    for (i = 0; i < 8; i++)
    {
        tmp = x[i] + y[i] + CF;

if (tmp != x[i])
            CF = (tmp < x[i] );

x[i] = tmp;
    }
}

 resulting code

 x86-64 gcc 8.3  (-O2)
-------------------------------------------------
add512(unsigned long long*, unsigned long long*):
        xor     eax, eax
        xor     ecx, ecx
.L3:
        mov     r8, QWORD PTR [rdi+rax]
        mov     rdx, QWORD PTR [rsi+rax]
        mov     r9d, ecx
        add     rdx, r8
        add     rdx, r9
        xor     r9d, r9d
        cmp     r8, rdx
        mov     QWORD PTR [rdi+rax], rdx
        seta    r9b
        cmovne  ecx, r9d
        add     rax, 8
        cmp     rax, 64
        jne     .L3
        ret


  x86-64 clang 6.0 (-O2)
 ------------------
add512(unsigned long long*, unsigned long long*):
        mov     rax, qword ptr [rsi]
        mov     rcx, qword ptr [rdi]
        add     rcx, rax
        setb    dl
        test    rax, rax
        setne   al
        and     al, dl
        mov     qword ptr [rdi], rcx
        movzx   edx, al
        mov     rcx, qword ptr [rdi + 8]
        mov     r9, qword ptr [rdi + 16]
        add     rdx, rcx
        add     rdx, qword ptr [rsi + 8]
        cmp     rdx, rcx
        setb    r8b
        je      .LBB0_2
        mov     eax, r8d
....
 on ARM64 (gcc -O2) platform both versions give the same suboptimal result
 --------------
add512(unsigned long long*, unsigned long long*):
        mov     ip, #0
        push    {r4, r5, r6, r7, lr}
        add     lr, r0, #64
.L3:
        ldmia   r0!, {r2-r3}
        ldmia   r1!, {r4-r5}
        adds    r6, r2, r4
        adc     r7, r3, r5
        adds    r4, r6, ip
        adc     r5, r7, #0
        cmp     r3, r5
        cmpeq   r2, r4
        beq     .L2
        movhi   ip, #1
        movls   ip, #0
.L2:
        cmp     lr, r0
        stmdb   r0, {r4-r5}
        bne     .L3
        pop     {r4, r5, r6, r7, pc}


 with -O3 flags gcc on both x86-64 and ARM  unrolls loop, by my opinion
unreasonably,  and make code a little bit faster

 I don't know PowerPC and I can't speak about PowerPC resulting code.
 -- --------------------------

clang unfortunately generate weird code. More effective code on Intel
x86-64 platform  can be achieved  by using intrinsics ( _addcarry_u64 ) or
using inline assembler.
x86-64 CPU of contemporary architecture give us adcx instruction  that
utilizes all the power of modern superscalar architecture by using two
carry bit channel in parallel.

 Notes. Some other parts of GOST engine module have different
implementations of similar big integer arithmetic.
i.e  "gosthash.c@int add_blocks(int n, byte * left, const byte * right) "
has it own.
Before making such deep optimization it would be better  to bring them all
 to unified version .

All this micro-optimizations of uncritical code sections can't  speedup the
hash update method more then 1%.

5. all this function have unnesasary intermediate buffers and  memory
transfers between context fields , input data and stack buffers
    this patch eliminates  the last .  Context has the "buffer" field that
can be  cover all the cases.
    Using only context buffer with fixed memory location and 64 byte
aligned  potentially improve CPU cache utilization.
    It require only one cache line  in contrast to stack buffers. having
 only 16 byte alignment on x86-64 and volatile address.

6.How I can reproduce your results?

 according to my measurements

commit 58a46b289d6b8df06072fc9c0304f4b2d3f4b051
Author: Ilya Shipitsin <chipitsine@gmail.com>
Date:   Sat Nov 9 17:13:49 2019 +0500

elapsed 28.0 seconds , speed : 0.18 Mhps  12.843 MBps
elapsed 28.8 seconds , speed : 0.17 Mhps  12.517 MBps
elapsed 29.2 seconds , speed : 0.17 Mhps  12.318 MBps
elapsed 28.1 seconds , speed : 0.18 Mhps  12.814 MBps

pull request

elapsed 28.1 seconds , speed : 0.18 Mhps  12.804 MBps
elapsed 27.7 seconds , speed : 0.18 Mhps  12.981 MBps
elapsed 28.1 seconds , speed : 0.18 Mhps  12.829 MBps
elapsed 28.1 seconds , speed : 0.18 Mhps  12.797 MBps

The overall performance of streebog digest is the same or a little  better
. It's too rough benchmark to observe the difference.

"gost2012_hash_block" stall significant  time in the LPSX transformation of
streebog algorithm (CPU crunch bound and already SSE2 optimized) . So,
elimination unnecessary memory movements and add512 function optimization
couldn't  considerably reduce CPU time.

This patch  rather reduce memory usage by elimination
 gost2012_hash_ctx.hash field (64 bytes ), extra stack buffers in pad,
stage2, stage3 (64 bytes each) without any performance and/or security
penalty. Memory movements have negative impact on CPU cache. I think,
tangible effect of the patch will see on heavily loaded machine only.

7.   //memcpy ...  - It's comment of existen code.  I forget remove this
lines before commit. Will be fixed.
   Can you point me other unformatted pieces ?

   I can split patch by two extracting  add512 function  refactoring and
new test scenario. Other  modifications are linked together  and should be
in one patch.
   .travis.yml  modification  was made for  run tests against openssl
1.1.1 .  because master branch of openssl is switched to  3.x

global:
- PREFIX=${HOME}/opt
- PATH=${PREFIX}/bin:${PATH}
- OPENSSL_BRANCH=master
- OPENSSL_BRANCH=OpenSSL_1_1_1-stable

**Comment by beldmit** [comment]
Many thanks for the contribution, but for the most cases I strongly prefer to have more maintainable code than the faster one in insignificant parts. 

The part to be optimized, if any, is smth on stage2. It takes 95+% of elapsed time in the case when data is longer than 256 bytes, and all the rest has almost no meaning. Sorry.

**Comment by vt-alt** [comment]
@ddulesov There's my quick and dirty patch to OpenSSL to support Streebog on `openssl speed`: https://gist.github.com/vt-alt/375932101b6c98ea1862b6381fcaa813

**Comment by beldmit** [comment]
OPENSSL_CONF=my.conf openssl speed -evp md_gost_12_256

**Comment by vt-alt** [comment]
Oh, yeah, forgot about `-evp`. Thx! (In case someone tries and fail with `md_gost_12_256`, algo name should be `md_gost12_256`.)

**Comment by ddulesov** [comment]
made tests on Intel i5-4210U 

collected series of 20  benchmarks as said before.
` for i in {1..20}; do /opt/openssl/bin/openssl speed -evp md_gost12_256 ; done`

for benchmark used

OpenSSL 1.1.1e-dev   ( current OpenSSL_1_1_1-stable branch )
commit b885981ed745106e530139af94c930e84c4a1baa

options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG

the patch
https://gist.github.com/vt-alt/375932101b6c98ea1862b6381fcaa813
has been applied as well.
 
compare openssl gost engine  origin/master and this patch (some small changes was made  ).
gost3411_2012

no  visible changes in speed. but there is no degradations

**Comment by ddulesov** [comment]
absolutely. and more important  almost all CPU time  consumes only one
function LPS. This function is well optimized, use SIMD and perform
computation on CPU registers. (however vectorization doesn't give any
speedup here )
By the way, this patch eliminate  unnecessary memory allocations and memory
transfers between  incoming  data and stack. Simplifying code this patch
makes it more clear, less  memory consuming, CPU cache friendly and
maintainable as well.

**Pull request closed without merging**
