### PR TITLE
Use frpintf(stderr, ...) instead of printf(...)

### PR DESCRIPTION
**Pull request by antonios-f**
When we use git cli in OS Linux, with enabled gost engine
git utility we got fatal error 
#365

### CODE REVIEW

**Comment by beldmit** [comment]
FreeBSD build failures are relevant

**Comment by antonios-f** [comment]
> FreeBSD build failures are relevant

I have corrected the commit, please take a look.

**Comment by beldmit** [comment]
LGTM. Could you please squash your commits?

**Comment by antonios-f** [comment]
Done.

**Comment by beldmit** [comment]
Merged. Thanks.

**Comment by antonios-f** [comment]
Is it needed to make PR for other branches?

**Pull request merged**
