### PR TITLE
openssl_1_0_2: fix building, cherry-picks from master

### PR DESCRIPTION
**Pull request by mikhailnov**
* fix building with OpenSSL 1.0.2t (commit 24390687fd24f6fa754fff83b5eb5ec0a314215e)
* cherry-picked useful commits from master

Result (after adjusting OpenSSL 1.0.2t by backporting https://github.com/openssl/openssl/commit/3b5e5172007d5eb30cec4269a0f763c9632afd06 and https://github.com/openssl/openssl/commit/55fc247a699be33153f27c06d304e6e60eeff980):

```
 openssl engine gost -c | tr ',' '\n'
(gost) Reference implementation of GOST engine
 [gost89
 gost89-cnt
 gost89-cnt-12
 gost89-cbc
 grasshopper-ecb
 grasshopper-cbc
 grasshopper-cfb
 grasshopper-ofb
 grasshopper-ctr
 magma-cbc
 magma-ctr
 id-tc26-cipher-gostr3412-2015-kuznyechik-ctracpkm
 md_gost94
 gost-mac
 md_gost12_256
 md_gost12_512
 gost-mac-12
 magma-mac
 grasshopper-mac
 gost2001
 gost-mac
 gost2012_256
 gost2012_512
 gost-mac-12
 magma-mac
 grasshopper-mac]
```

```
openssl version
OpenSSL 1.0.2t  10 Sep 2019
```

Tests:

```
+ ./test_grasshopper
Encryption test from GOST R 34.13-2015 [ecb] 
  c[64] =  7f679d90bebc24305a468d42b9d4edcd b429912c6e0032f9285452d76718d08b f0ca33549d247ceef3f5a5313bd4b157 d0b09ccde830b9eb3a02c4c5aa8ada98
Test passed
Chunked encryption test from GOST R 34.13-2015 [ecb] 
  c[64] =  7f679d90bebc24305a468d42b9d4edcd b429912c6e0032f9285452d76718d08b f0ca33549d247ceef3f5a5313bd4b157 d0b09ccde830b9eb3a02c4c5aa8ada98
Test passed
Decryption test from GOST R 34.13-2015 [ecb] 
  d[64] =  1122334455667700ffeeddccbbaa9988 00112233445566778899aabbcceeff0a 112233445566778899aabbcceeff0a00 2233445566778899aabbcceeff0a0011
Test passed
Encryption test from GOST R 34.13-2015 [ctr] 
  c[64] =  f195d8bec10ed1dbd57b5fa240bda1b8 85eee733f6a13e5df33ce4b33c45dee4 a5eae88be6356ed3d5e877f13564a3a5 cb91fab1f20cbab6d1c6d15820bdba73
Test passed
Chunked encryption test from GOST R 34.13-2015 [ctr] 
  c[64] =  f195d8bec10ed1dbd57b5fa240bda1b8 85eee733f6a13e5df33ce4b33c45dee4 a5eae88be6356ed3d5e877f13564a3a5 cb91fab1f20cbab6d1c6d15820bdba73
Test passed
Decryption test from GOST R 34.13-2015 [ctr] 
  d[64] =  1122334455667700ffeeddccbbaa9988 00112233445566778899aabbcceeff0a 112233445566778899aabbcceeff0a00 2233445566778899aabbcceeff0a0011
Test passed
Stream encryption test from GOST R 34.13-2015 [ctr] 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Test passed
Encryption test from GOST R 34.13-2015 [ctr-no-acpkm] 
  c[64] =  f195d8bec10ed1dbd57b5fa240bda1b8 85eee733f6a13e5df33ce4b33c45dee4 a5eae88be6356ed3d5e877f13564a3a5 cb91fab1f20cbab6d1c6d15820bdba73
Test passed
Chunked encryption test from GOST R 34.13-2015 [ctr-no-acpkm] 
  c[64] =  f195d8bec10ed1dbd57b5fa240bda1b8 85eee733f6a13e5df33ce4b33c45dee4 a5eae88be6356ed3d5e877f13564a3a5 cb91fab1f20cbab6d1c6d15820bdba73
Test passed
Decryption test from GOST R 34.13-2015 [ctr-no-acpkm] 
  d[64] =  1122334455667700ffeeddccbbaa9988 00112233445566778899aabbcceeff0a 112233445566778899aabbcceeff0a00 2233445566778899aabbcceeff0a0011
Test passed
Stream encryption test from GOST R 34.13-2015 [ctr-no-acpkm] 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Test passed
Encryption test from R 23565.1.017-2018 [ctracpkm] 
  c[112] =  f195d8bec10ed1dbd57b5fa240bda1b8 85eee733f6a13e5df33ce4b33c45dee4 4bceeb8f646f4c55001706275e85e800 587c4df568d094393e4834afd0805046 cf30f57686aeece11cfc6c316b8a896e dffd07ec813636460c4f3b743423163e 6409a9c282fac8d469d221e7fbd6de5d
Test passed
Chunked encryption test from R 23565.1.017-2018 [ctracpkm] 
  c[112] =  f195d8bec10ed1dbd57b5fa240bda1b8 85eee733f6a13e5df33ce4b33c45dee4 4bceeb8f646f4c55001706275e85e800 587c4df568d094393e4834afd0805046 cf30f57686aeece11cfc6c316b8a896e dffd07ec813636460c4f3b743423163e 6409a9c282fac8d469d221e7fbd6de5d
Test passed
Decryption test from R 23565.1.017-2018 [ctracpkm] 
  d[112] =  1122334455667700ffeeddccbbaa9988 00112233445566778899aabbcceeff0a 112233445566778899aabbcceeff0a00 2233445566778899aabbcceeff0a0011 33445566778899aabbcceeff0a001122 445566778899aabbcceeff0a00112233 5566778899aabbcceeff0a0011223344
Test passed
Stream encryption test from R 23565.1.017-2018 [ctracpkm] 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Test passed
Encryption test from R 23565.1.017-2018 [acpkm-Master] 
  c[144] =  0cabf1f2efbc4ac16048df1a24c605b2 c0d1673d7586a8ec0dd42c45a4f95bae 0f2e2617e47148680fc3e6178df2c137 c9dda89cffa491feadd9b3eab703bb31 bc7e927f0494729f51b49d3df9c94608 00fbbcf5edee610ea02f01093c7bc742 d7d6271501b177775263c2a3495a8318 a81c79a04f29660ea3fda874c630799e 142c577914fea90d3bc2502e833685d9
Test passed
Chunked encryption test from R 23565.1.017-2018 [acpkm-Master] 
  c[144] =  0cabf1f2efbc4ac16048df1a24c605b2 c0d1673d7586a8ec0dd42c45a4f95bae 0f2e2617e47148680fc3e6178df2c137 c9dda89cffa491feadd9b3eab703bb31 bc7e927f0494729f51b49d3df9c94608 00fbbcf5edee610ea02f01093c7bc742 d7d6271501b177775263c2a3495a8318 a81c79a04f29660ea3fda874c630799e 142c577914fea90d3bc2502e833685d9
Test passed
Decryption test from R 23565.1.017-2018 [acpkm-Master] 
  d[144] =  00000000000000000000000000000000 00000000000000000000000000000000 00000000000000000000000000000000 00000000000000000000000000000000 00000000000000000000000000000000 00000000000000000000000000000000 00000000000000000000000000000000 00000000000000000000000000000000 00000000000000000000000000000000
Test passed
Encryption test from GOST R 34.13-2015 [ofb] 
  c[64] =  81800a59b1842b24ff1f795e897abd95 779146db2d93a94ed93cf68b32397f19 e93c9e57441d870545f24036a58ceea3 cf3f0061d56423545b960d864cc868da
Test passed
Chunked encryption test from GOST R 34.13-2015 [ofb] 
  c[64] =  81800a59b1842b24ff1f795e897abd95 779146db2d93a94ed93cf68b32397f19 e93c9e57441d870545f24036a58ceea3 cf3f0061d56423545b960d864cc868da
Test passed
Decryption test from GOST R 34.13-2015 [ofb] 
  d[64] =  1122334455667700ffeeddccbbaa9988 00112233445566778899aabbcceeff0a 112233445566778899aabbcceeff0a00 2233445566778899aabbcceeff0a0011
Test passed
Stream encryption test from GOST R 34.13-2015 [ofb] 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Test passed
Encryption test from GOST R 34.13-2015 [cbc] 
  c[64] =  689972d4a085fa4d90e52e3d6d7dcc27 abf170b2b226c3010ccfa136d659cdaa ca719272ab1d438e15507d521ecd5522 e01108ff8d9d3a6d8ca2a533fa614e71
Test passed
Chunked encryption test from GOST R 34.13-2015 [cbc] 
  c[64] =  689972d4a085fa4d90e52e3d6d7dcc27 abf170b2b226c3010ccfa136d659cdaa ca719272ab1d438e15507d521ecd5522 e01108ff8d9d3a6d8ca2a533fa614e71
Test passed
Decryption test from GOST R 34.13-2015 [cbc] 
  d[64] =  1122334455667700ffeeddccbbaa9988 00112233445566778899aabbcceeff0a 112233445566778899aabbcceeff0a00 2233445566778899aabbcceeff0a0011
Test passed
Encryption test from GOST R 34.13-2015 [cfb] 
  c[64] =  81800a59b1842b24ff1f795e897abd95 68c1b99c4df59cc7951e3739b5b3cdbf 073f4dd2d6deb3cfb026545f7af1d8e8 e1c852e9a8567162dbb5da7f66dea926
Test passed
Chunked encryption test from GOST R 34.13-2015 [cfb] 
  c[64] =  81800a59b1842b24ff1f795e897abd95 68c1b99c4df59cc7951e3739b5b3cdbf 073f4dd2d6deb3cfb026545f7af1d8e8 e1c852e9a8567162dbb5da7f66dea926
Test passed
Decryption test from GOST R 34.13-2015 [cfb] 
  d[64] =  1122334455667700ffeeddccbbaa9988 00112233445566778899aabbcceeff0a 112233445566778899aabbcceeff0a00 2233445566778899aabbcceeff0a0011
Test passed
OMAC test from GOST R 34.13-2015
  MAC[8] =  336f4d296059fbe3
Test passed
OMAC-ACPKM test from R 1323565.1.017-2018 A.4.1
  MAC[16] =  b5367f47b62b995eeb2a648c5843145e
Test passed
OMAC-ACPKM test from R 1323565.1.017-2018 A.4.2
  MAC[16] =  fbb8dcee45bea67c35f58c5700898e5d
Test passed
= All tests passed!
```

When running tests above, I disabled test for cipher `GOST2012-GOST8912-GOST8912`. Making it work seems to require a lot of backports to OpenSSL 1.0.2. I did not include my disablement into this pull request, because I am not sure that I am right that this cipher must not work with OpenSSL 1.0.2.

P.S. Здесь странная структура бранчей, содержимое этого бранча оказалось полезным, возвращаю обратно то, как его доработал, не знаю, нужно или нет это здесь, возможно, стоит переименовать бранч.

### CODE REVIEW

**Comment by beldmit** [comment]
As openssl 1.0.2 itself is out of support now, there is no sense to apply this patch.

**Comment by mikhailnov** [comment]
sounds reasonable, then close this PR

**Comment by beldmit** [comment]
Thanks anyway! Happy New Year!

**Comment by mikhailnov** [comment]
Happy new year with OpenSSL 1.0.2 - what a good wish :)

**Pull request closed without merging**
