### PR TITLE
Add CI builds on MacOS 11 (BigSur)

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
There's too little MacOS building...

**Comment by levitte** [comment]
That's a lot of failures...  I'm pretty sure it works better in pur github action form, having done the same thing for other stuff.

**Comment by beldmit** [comment]
You've missed installing cpanm and Test::V0 (as in macos-asan)

**Comment by levitte** [comment]
> You've missed installing cpanm and Test::V0 (as in macos-asan)

I didn't exactly miss it, I was trying to see how `.github/before_script.sh` does on MacOS.  It does try to install cpanm, but apparently doesn't get it quite right.  You can see that if you look at the logs.
`perl-actions/install-with-cpanm@v1` works differently, it downloads `cpanm` as a standalone executable (as described in https://github.com/miyagawa/cpanminus/tree/devel/App-cpanminus#downloading-the-standalone-executable), and simply copies it to the proper location for perl site scripts.  You can see for yourself exactly how it does that if you look at the "macos-asan-openssl-master" job, by looking more closely at the "install cpanm and Test::V0" step.

**Comment by levitte** [comment]
I've modified `.github/before_script.sh` to work more like the corresponding Github action

**Comment by beldmit** [comment]
Is it still WIP?

**Comment by levitte** [comment]
I've cleaned up the commits, it's ready for review / merge

**Comment by beldmit** [comment]
Merged. Many thanks!

**Pull request merged**
