### PR TITLE
Also build gost-engine in library form

### PR DESCRIPTION
**Pull request by levitte**
In this form, the GOST engine isn't loadable through OpenSSL's dynamic
ENGINE loader, but directly as its own function, ENGINE_load_gost().
After making that call, the engine functionality can be used as usual.

This also rearranges the code in gost_eng.c, as the binding
functionality was spread around in the file.  Now, it's all nicely
tucked at the end.

### CODE REVIEW

**Comment by beldmit** [comment]
So it's the 3rd build option, isn't it?

**Comment by levitte** [comment]
> 3rd build option

Not sure I understand what that means

**Comment by beldmit** [comment]
I mean, dynamic loadable, directly loadable, and provider

**Comment by levitte** [comment]
I've already made the provider directly linkable too, so there will be 4 options in total (going down to 2 when engine support goes away)

**Comment by vt-alt** [comment]
I tested it and compiled an example program and so far so good! It even requires properly `libcrypto.so.3` itself.

**Comment by levitte** [comment]
Note that I haven't added any installation instructions in CMakeLists.txt, the cmake complexities there are still a mystery to me, so if someone could help out with that part, I'd be grateful

**Comment by levitte** [comment]
I figured out the install stuff, so it's now modified in a way that I hope is suitable

**Comment by levitte** [comment]
Of course, this also gets hit by the regression that @beldmit identified in openssl/openssl#14263

**Comment by beldmit** [comment]
@levitte, speaking frankly, I don't understand when this PR is finished. I usually commit the PRs either when I understand them or after the explicit nudge :)

**Comment by levitte** [comment]
> I don't understand when this PR is finished

Sorry, I should have been more explicit.  I consider this PR finished now.

**Comment by beldmit** [comment]
Merged. Many thanks!

**Comment by vt-alt** [comment]
Yeah, thanks much!

**Pull request merged**
